syntax = "proto3";

package exchange;

message AssetBalance {
  int64 available = 1;
  int64 locked = 2;
}

// Request sent from API Gateway to Risk Check
message OrderRequest {
  string user_id = 1;
  string order_id = 2;
  int64 price = 3;        // Scaled Satoshi integer (10^8)
  int64 quantity = 4;     // Scaled Satoshi integer (10^8)
  string side = 5;        // "BUY" | "SELL"
  string type = 6;        // "limit" | "market"
  string base_asset = 7;
  string quote_asset = 8;
}

// Request sent from API Gateway to Risk Check
message BalanceRequest {
  string user_id = 1;
  string tx_id = 2;
  string asset = 3;
  string type = 4;
  int64 amount = 5;
}

// Response from Risk Check back to Gateway
message RiskCheckOrderResponse {
  bool success = 1;
  string message = 2;
  string order_id = 3;
}

// Response from Risk Check back to Gateway
message RiskCheckUpdateBalanceResponse {
  bool success = 1;
  string message = 2;
  string tx_id = 3;
}

// Response from Risk Check back to Gateway
message RiskCheckfetchUserBalanceResponse {
  bool success = 1;
  string message = 2;
  string user_id = 3;
  map<string, AssetBalance> balances = 4; // {"USDT": {available, locked}, "BTC": {available, locked}}
}

// gRPC Service exposed by Risk Check Service
service RiskService {
  rpc ValidateAndProcessOrder (OrderRequest) returns (RiskCheckOrderResponse);
  rpc ValidateAndUpdateUserBalance (BalanceRequest) returns (RiskCheckUpdateBalanceResponse);
  rpc fetchUserBalance (BalanceRequest) returns (RiskCheckfetchUserBalanceResponse);
}
